# Auto-generated configuration for AWS Account: 970597968483
# Generated by precheck.py on $(date)

project     = "kayak"
environment = "dev"
region      = "us-east-1"

tags = {
  Owner   = "data-team"
  Account = "970597968483"
}

broker_subnet_ids = [
  "subnet-0f198d11c08495c48",
  "subnet-02c9aef989658300e",
  "subnet-0dc67217d852e887f",
]

broker_security_group_ids = [
  "sg-0977923925a890390",
]

msk_instance_type   = "kafka.t3.small"
msk_broker_count    = 3
msk_ebs_volume_size = 10

# Leave empty to use the AWS managed key for MSK encryption
msk_kms_key_arn = ""

log_retention_in_days = 7

# Bastion Configuration
vpc_id              = "vpc-00e1faaa7552b7fb4"
bastion_subnet_id   = "subnet-0f198d11c08495c48"
bastion_instance_type = "t3.nano"
