# Auto-generated configuration for AWS Account: 723609008063
# Generated by precheck.py on $(date)

project     = "kayak"
environment = "dev"
region      = "us-east-1"

tags = {
  Owner   = "data-team"
  Account = "723609008063"
}

broker_subnet_ids = [
  "subnet-0d48ac62a7bbef76d",
  "subnet-061d78dc9c84a1a50",
  "subnet-049ee67b26be450d9",
]

broker_security_group_ids = [
  "sg-01391f21027d15533",
]

msk_instance_type   = "kafka.t3.small"
msk_broker_count    = 3
msk_ebs_volume_size = 10

# Leave empty to use the AWS managed key for MSK encryption
msk_kms_key_arn = ""

log_retention_in_days = 7
